from .create_keypair import CreateKeyPairAction
from .attach_keypairs import AttachKeyPairsAction
from .detach_keypairs import DetachKeyPairsAction
from .describe_keypairs import DescribeKeyPairsAction
from .modify_keypair_attributes import ModifyKeyPairAttributesAction
from .delete_keypairs import DeleteKeyPairsAction
